packages:
  - apps/*

onlyBuiltDependencies:
  - better-sqlite3

ignoredBuiltDependencies:
  - '@playwright/browser-chromium'
  - '@swc/core'
  - esbuild
  - onnxruntime-node
  - protobufjs
  - sharp
